### ISSUE TITLE
ST-LINKv3 compatibility

### ISSUE THREAD

**Issue by Disasm** [korken89/hs-probe#2]
As far as I can tell from different sources including the [schematics](https://raw.githubusercontent.com/RadioOperator/CMSIS-DAP_for_STLINK-V3MINI/master/STLINK-V3MINI/Sch/STLINK-V3E_Sch_from_G431sch.jpg) and STLINK-V3SET user manual, pin 1 and pin 2 of the STDC14 connector are used as power output, while pin 3 is an input to stlink.

I'd like suggest the following changes in order to improve stlink-v3 compatibility and use consistent signalling across stlinkv3 and hs-probe.
* since hs-probe has a separate power supply for 3.3V on target, it's better to connect it to pin 2 instead of pin 3.
* use pin 3 of the STDC14 connector to measure target voltage.
* optionally make pin 1 of the STDC14 connector switchable, ST uses STMPS2151STR to control it.

**Comment by korken89** [comment]
This has been updated to follow, thanks for the feedback!
