### ISSUE TITLE
Connect USB FS pins to the USB connector

### ISSUE THREAD

**Issue by Disasm** [korken89/hs-probe#3]
We have a few reasons to use USB FS at the moment:
* Embedded DFU bootloader only supports USB FS peripheral
* Rust USB driver is not ready yet to handle USB HS

It would be great to allow the firmware to use both USB FS and HS peripherals via the same USB connector, and switch between them.
* Use USB switch (like USB3740B suggested by @korken89). Probably it's a good idea to make USB FS channel enabled by default so that the DFU bootloader can work without any knowledge about this switch.
* Use different (5V-tolerant) pins for LED2 and LED3 to not interfere with USB FS signalling.

**Comment by korken89** [comment]
This has been added via USB Mux, thanks for the feedback!
